EStore/Controllers/MembersController.cs
using BusinessObject;
using DataAccess.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.Json;

namespace EStore.Controllers
{
    public class MembersController : Controller
    {
        private IMemberRepository memberRepository = new MemberRepository();

        // GET: MembersController
        public ActionResult Index()
        {
            var memberId = HttpContext.Session.GetInt32("MemberId");
            if (memberId == null)
                return RedirectToAction("Index", "Login");
            if (memberId == 0)
                return View(memberRepository.GetAll());
            return View(memberRepository.GetAll().Where(m => m.MemberId == memberId));
        }

        // GET: MembersController/Details/5
        public ActionResult Details(int id)
        {
            var member = memberRepository.GetById(id);
            if (member == null)
                return NotFound();
            return View(member);
        }

        // GET: MembersController/Create
        public ActionResult Create()
        {
            ViewBag.Country = GetCountryList();
            return View();
        }

        // POST: MembersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Member member)
        {
            try
            {
                if (ModelState.IsValid)
                    memberRepository.Insert(member);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Country = GetCountryList();
                ViewBag.Message = ex.Message;
                return View(member);
            }
        }

        // GET: MembersController/Edit/5
        public ActionResult Edit(int id)
        {
            var member = memberRepository.GetById(id);
            if (member == null)
                return NotFound();

            ViewBag.Country = GetCountryList();
            return View(member);
        }

        // POST: MembersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Member member)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    member.MemberId = id;
                    memberRepository.Update(member);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Country = GetCountryList();
                ViewBag.Message = ex.Message;
                return View(member);
            }
        }

        // GET: MembersController/Delete/5
        public ActionResult Delete(int id)
        {
            var member = memberRepository.GetById(id);
            if (member == null)
                return NotFound();
            return View(member);
        }

        // POST: MembersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Member member)
        {
            try
            {
                memberRepository.Remove(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(member);
            }
        }

        private IEnumerable<SelectListItem> GetCountryList()
        {
            string path = @"countries.json";
            var data = System.IO.File.ReadAllText(path);
            var countries = JsonSerializer.Deserialize<Dictionary<string, string>>(data);
            return countries
                ?.Values
                ?.OrderBy(country => country)
                ?.Select(country => new SelectListItem(country, country))
                ?? new List<SelectListItem>(0);
        }
    }
}

EStore/Controllers/OrderDetailsController.cs
using BusinessObject;
using DataAccess.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;

namespace EStore.Controllers
{
    [Route("[controller]")]
    public class OrderDetailsController : Controller
    {
        IOrderDetailRepository orderDetailRepository = new OrderDetailRepository();
        IProductRepository productRepository = new ProductRepository();

        // GET: OrderDetailsController
        [HttpGet("{orderId}")]
        public ActionResult Index(int orderId)
        {
            ViewBag.OrderId = orderId;
            return View(orderDetailRepository.GetByOrderId(orderId));
        }

        // GET: OrderDetailsController/Details/5
        [HttpGet("{orderId}/Details/{productId}")]
        public ActionResult Details(int orderId, int productId)
        {
            var orderDetail = orderDetailRepository.GetById(orderId, productId);
            if (orderDetail == null)
                return NotFound();
            return View(orderDetail);
        }

        // GET: OrderDetailsController/Create
        [HttpGet("{orderId}/Create")]
        public ActionResult Create(int orderId)
        {
            ViewBag.ProductId = GetProductList();
            return View(new OrderDetail { OrderId = orderId });
        }

        // POST: OrderDetailsController/Create
        [HttpPost("{orderId}/Create")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int orderId, OrderDetail orderDetail)
        {
            try
            {
                orderDetail.OrderId = orderId;
                orderDetailRepository.Insert(orderDetail);
                return RedirectToAction(nameof(Index), new { orderId });
            }
            catch (Exception ex)
            {
                ViewBag.ProductId = GetProductList();
                ViewBag.Message = ex.Message;
                return View(orderDetail);
            }
        }

        // GET: OrderDetailsController/Edit/5
        [HttpGet("{orderId}/Edit/{productId}")]
        public ActionResult Edit(int orderId, int productId)
        {
            var orderDetail = orderDetailRepository.GetById(orderId, productId);
            if (orderDetail == null)
                return NotFound();
            return View(orderDetail);
        }

        // POST: OrderDetailsController/Edit/5
        [HttpPost("{orderId}/Edit/{productId}")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int orderId, int productId, OrderDetail orderDetail)
        {
            try
            {
                orderDetail.OrderId = orderId;
                orderDetail.ProductId = productId;
                orderDetailRepository.Update(orderDetail);
                return RedirectToAction(nameof(Index), new { orderId });
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(orderDetail);
            }
        }

        // GET: OrderDetailsController/Delete/5
        [HttpGet("{orderId}/Delete/{productId}")]
        public ActionResult Delete(int orderId, int productId)
        {
            var orderDetail = orderDetailRepository.GetById(orderId, productId);
            if (orderDetail == null)
                return NotFound();
            return View(orderDetail);
        }

        // POST: OrderDetailsController/Delete/5
        [HttpPost("{orderId}/Delete/{productId}")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int orderId, int productId, OrderDetail orderDetail)
        {
            try
            {
                orderDetailRepository.Remove(orderId, productId);
                return RedirectToAction(nameof(Index), new { orderId });
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(orderDetail);
            }
        }

        private IEnumerable<SelectListItem> GetProductList()
        {
            return productRepository.GetAll()
                .Select(p => new SelectListItem(p.ProductName, p.ProductId.ToString()));
        }
    }
}

EStore/Controllers/OrdersController.cs
using BusinessObject;
using DataAccess.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EStore.Controllers
{
    public class OrdersController : Controller
    {
        IOrderRepository orderRepository = new OrderRepository();
        IMemberRepository memberRepository = new MemberRepository();
        IOrderDetailRepository orderDetailRepository = new OrderDetailRepository();

        // GET: OrdersController
        public ActionResult Index()
        {
            var memberId = HttpContext.Session.GetInt32("MemberId");
            if (memberId == null)
                return RedirectToAction("Index", "Login");
            if (memberId == 0)
                return View(orderRepository.GetAll());
            return View(orderRepository.GetByMemberId(memberId.Value));
        }

        // GET: OrdersController/Details/5
        public ActionResult Details(int id)
        {
            var order = orderRepository.GetById(id);
            if (order == null)
                return NotFound();
            return View(order);
        }

        // GET: OrdersController/Create
        public ActionResult Create()
        {
            ViewBag.MemberId = GetMemberList();
            return View();
        }

        // POST: OrdersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Order order)
        {
            try
            {
                orderRepository.Insert(order);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.MemberId = GetMemberList();
                ViewBag.Message = ex.Message;
                return View(order);
            }
        }

        // GET: OrdersController/Edit/5
        public ActionResult Edit(int id)
        {
            var order = orderRepository.GetById(id);
            if (order == null)
                return NotFound();

            ViewBag.MemberId = GetMemberList();
            return View(order);
        }

        // POST: OrdersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Order order)
        {
            try
            {
                order.OrderId = id;
                orderRepository.Update(order);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.MemberId = GetMemberList();
                ViewBag.Message = ex.Message;
                return View(order);
            }
        }

        // GET: OrdersController/Delete/5
        public ActionResult Delete(int id)
        {
            var order = orderRepository.GetById(id);
            if (order == null)
                return NotFound();
            return View(order);
        }

        // POST: OrdersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Order order)
        {
            try
            {
                orderRepository.Remove(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(order);
            }
        }

        public ActionResult Report(DateTime? from, DateTime? to)
        {
            if (from == null || to == null)
                return View();

            DateTime fromDate = from.Value;
            DateTime toDate = to.Value;

            IEnumerable<Order> orders = orderRepository.GetAll()
                .Where(o => fromDate.Date.CompareTo(o.OrderDate.Date) <= 0 && o.OrderDate.Date.CompareTo(toDate.Date) <= 0)
                .OrderByDescending(o => o.OrderDate);
            IEnumerable<OrderDetail> details = orderDetailRepository.GetBetweenDays(fromDate, toDate);

            ViewBag.Orders = orders.Count();
            ViewBag.SoldProducts = details.Sum(d => d.Quantity);
            ViewBag.Customers = orders.DistinctBy(o => o.MemberId).Count();
            ViewBag.Turnover = details.Sum(d => d.UnitPrice * d.Quantity);

            ViewBag.From = fromDate.ToString("yyyy-MM-dd");
            ViewBag.To = toDate.ToString("yyyy-MM-dd");
            return View(orders);
        }

        private IEnumerable<SelectListItem> GetMemberList()
        {
            return memberRepository.GetAll()
                .Select(m => new SelectListItem(m.Email, m.MemberId.ToString()));
        }
    }
}

EStore/Views/Orders/Create.cshtml
@model BusinessObject.Order

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>
<p>@ViewBag.Message</p>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MemberId" class="control-label">Member</label>
                <select asp-for="MemberId" class ="form-control" asp-items="ViewBag.MemberId"></select>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequiredDate" class="control-label"></label>
                <input asp-for="RequiredDate" class="form-control" />
                <span asp-validation-for="RequiredDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippedDate" class="control-label"></label>
                <input asp-for="ShippedDate" class="form-control" />
                <span asp-validation-for="ShippedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Freight" class="control-label"></label>
                <input asp-for="Freight" class="form-control" />
                <span asp-validation-for="Freight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EStore/Views/Orders/Delete.cshtml
@model BusinessObject.Order

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>
<p>@ViewBag.Message</p>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequiredDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequiredDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShippedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShippedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Freight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Freight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd class = "col-sm-10">
            <a asp-controller="Members" asp-action="Details" asp-route-id="@Model?.MemberId">
                @Html.DisplayFor(model => model.Member.Email)
            </a>
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EStore/Views/Orders/Details.cshtml
@model BusinessObject.Order

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequiredDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequiredDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShippedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShippedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Freight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Freight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd class = "col-sm-10">
            <a asp-controller="Members" asp-action="Details" asp-route-id="@Model?.MemberId">
                @Html.DisplayFor(model => model.Member.Email)
            </a>
        </dd>
        <dt class="col-sm-2">
            <a asp-controller="OrderDetails" asp-action="Index" asp-route-orderId="@Model?.OrderId" class="btn btn-info">OrderDetail</a>
        </dt>
    </dl>
</div>
<div>
    @if (int.Equals(Context.Session.GetInt32("MemberId"), 0))
    {
        <text>
            <a asp-action="Edit" asp-route-id="@Model?.OrderId">Edit</a> |
        </text>
    }
    <a asp-action="Index">Back to List</a>
</div>

EStore/Views/Orders/Edit.cshtml
@model BusinessObject.Order

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>
<p>@ViewBag.Message</p>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderId" />
            <div class="form-group">
                <label asp-for="MemberId" class="control-label">Member</label>
                <select asp-for="MemberId" class="form-control" asp-items="ViewBag.MemberId"></select>
                <span asp-validation-for="MemberId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequiredDate" class="control-label"></label>
                <input asp-for="RequiredDate" class="form-control" />
                <span asp-validation-for="RequiredDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippedDate" class="control-label"></label>
                <input asp-for="ShippedDate" class="form-control" />
                <span asp-validation-for="ShippedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Freight" class="control-label"></label>
                <input asp-for="Freight" class="form-control" />
                <span asp-validation-for="Freight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EStore/Views/Orders/Index.cshtml
@model IEnumerable<BusinessObject.Order>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Orders</h1>

@if (int.Equals(Context.Session.GetInt32("MemberId"), 0))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequiredDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShippedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Freight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Member)
            </th>
            <th>OrderDetail</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RequiredDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShippedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Freight)
            </td>
            <td>
                <a asp-controller="Members" asp-action="Details" asp-route-id="@item.MemberId">
                    @Html.DisplayFor(modelItem => item.Member.Email)
                </a>
            </td>
            <td>
                <a asp-controller="OrderDetails" asp-action="Index" asp-route-orderId="@item.OrderId">View</a>
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.OrderId">Details</a> |
            @if (int.Equals(Context.Session.GetInt32("MemberId"), 0)) {
                <text>
                    <a asp-action="Edit" asp-route-id="@item.OrderId">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.OrderId">Delete</a>
                </text>
            }
            </td>
        </tr>
}
    </tbody>
</table>

EStore/Views/Orders/Report.cshtml
@model IEnumerable<BusinessObject.Order>

@{
    ViewData["Title"] = "Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Report</h1>

<form asp-action="Report" method="get">
    <label>From</label>
    <input type="date" name="from" value="@ViewBag.From" />
    <label>To</label>
    <input type="date" name="to" value="@ViewBag.To" />
    <input type="submit" value="Generate" class="btn btn-primary" />
</form>
<hr />

<dl class="row">
    <dt class="col-md-2">Orders</dt>
    <dd class="col-md-10">
        @ViewBag.Orders
    </dd>
    <dt class="col-md-2">Sold products</dt>
    <dd class="col-md-10">
        @ViewBag.SoldProducts
    </dd>
    <dt class="col-md-2">Customers</dt>
    <dd class="col-md-10">
        @ViewBag.Customers
    </dd>
    <dt class="col-md-2">Turnover</dt>
    <dd class="col-md-10">
        @ViewBag.Turnover
    </dd>
</dl>

@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.OrderDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RequiredDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ShippedDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Freight)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Member)
                </th>
                <th>OrderDetail</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RequiredDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShippedDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Freight)
                    </td>
                    <td>
                        <a asp-controller="Members" asp-action="Details" asp-route-id="@item.MemberId">
                            @Html.DisplayFor(modelItem => item.Member.Email)
                        </a>
                    </td>
                    <td>
                        <a asp-controller="OrderDetails" asp-action="Index" asp-route-orderId="@item.OrderId">View</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}