EStore/Controllers/LoginController.cs
using BusinessObject;
using DataAccess.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace eStore.Controllers
{
    public class LoginController : Controller
    {
        [AllowAnonymous]
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index([FromForm] string email, [FromForm] string password)
        {
            try
            {
                IMemberRepository memberRepository = new MemberRepository();
                Member loginMember = memberRepository.Login(email, password);

                if (loginMember != null)
                {
                        HttpContext.Session.SetInt32("MemberId", loginMember.MemberId);
                }
                
                return RedirectToAction("Index", "Members");
            }
            catch (Exception ex)
            {
                ViewBag.Email = email;
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        public IActionResult UserAccessDenied()
        {
            return View();
        }
    }
}

EStore/Controllers/LogoutController.cs
using Microsoft.AspNetCore.Mvc;

namespace EStore.Controllers
{
    public class LogoutController : Controller
    {
        public IActionResult Index()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Login");
        }
    }
}

EStore/Controllers/OrdersController.cs
using BusinessObject;
using DataAccess.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EStore.Controllers
{
    public class OrdersController : Controller
    {
        IOrderRepository orderRepository = new OrderRepository();
        IMemberRepository memberRepository = new MemberRepository();
        IOrderDetailRepository orderDetailRepository = new OrderDetailRepository();

        // GET: OrdersController
        public ActionResult Index()
        {
            var memberId = HttpContext.Session.GetInt32("MemberId");
            if (memberId == null)
                return RedirectToAction("Index", "Login");
            if (memberId == 0)
                return View(orderRepository.GetAll());
            return View(orderRepository.GetByMemberId(memberId.Value));
        }

        // GET: OrdersController/Details/5
        public ActionResult Details(int id)
        {
            var order = orderRepository.GetById(id);
            if (order == null)
                return NotFound();
            return View(order);
        }

        // GET: OrdersController/Create
        public ActionResult Create()
        {
            ViewBag.MemberId = GetMemberList();
            return View();
        }

        // POST: OrdersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Order order)
        {
            try
            {
                orderRepository.Insert(order);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.MemberId = GetMemberList();
                ViewBag.Message = ex.Message;
                return View(order);
            }
        }

        // GET: OrdersController/Edit/5
        public ActionResult Edit(int id)
        {
            var order = orderRepository.GetById(id);
            if (order == null)
                return NotFound();

            ViewBag.MemberId = GetMemberList();
            return View(order);
        }

        // POST: OrdersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Order order)
        {
            try
            {
                order.OrderId = id;
                orderRepository.Update(order);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.MemberId = GetMemberList();
                ViewBag.Message = ex.Message;
                return View(order);
            }
        }

        // GET: OrdersController/Delete/5
        public ActionResult Delete(int id)
        {
            var order = orderRepository.GetById(id);
            if (order == null)
                return NotFound();
            return View(order);
        }

        // POST: OrdersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Order order)
        {
            try
            {
                orderRepository.Remove(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(order);
            }
        }

        public ActionResult Report(DateTime? from, DateTime? to)
        {
            if (from == null || to == null)
                return View();

            DateTime fromDate = from.Value;
            DateTime toDate = to.Value;

            IEnumerable<Order> orders = orderRepository.GetAll()
                .Where(o => fromDate.Date.CompareTo(o.OrderDate.Date) <= 0 && o.OrderDate.Date.CompareTo(toDate.Date) <= 0)
                .OrderByDescending(o => o.OrderDate);
            IEnumerable<OrderDetail> details = orderDetailRepository.GetBetweenDays(fromDate, toDate);

            ViewBag.Orders = orders.Count();
            ViewBag.SoldProducts = details.Sum(d => d.Quantity);
            ViewBag.Customers = orders.DistinctBy(o => o.MemberId).Count();
            ViewBag.Turnover = details.Sum(d => d.UnitPrice * d.Quantity);

            ViewBag.From = fromDate.ToString("yyyy-MM-dd");
            ViewBag.To = toDate.ToString("yyyy-MM-dd");
            return View(orders);
        }

        private IEnumerable<SelectListItem> GetMemberList()
        {
            return memberRepository.GetAll()
                .Select(m => new SelectListItem(m.Email, m.MemberId.ToString()));
        }
    }
}

EStore/Controllers/ProductsController.cs
using BusinessObject;
using DataAccess.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EStore.Controllers
{
    public class ProductsController : Controller
    {
        IProductRepository productRepository = new ProductRepository();

        // GET: ProductsController
        //public ActionResult Index()
        //{
        //    return View(productRepository.GetAll());
        //}

        public ActionResult Index(string? name, int? price)
        {
            SelectListItem[] priceRanges =
            {
                new SelectListItem("All", "0"),
                new SelectListItem("0 - 999,999", "1"),
                new SelectListItem("1,000,000 - 9,999,999", "2"),
                new SelectListItem("10,000,000 -", "3")
            };
            ViewBag.PriceRanges = priceRanges;

            IEnumerable<Product> products = productRepository.GetAll();
            if (name != null)
            {
                ViewBag.SearchName = name;
                return View(products.Where(p => p.ProductName
                    .Contains(name, StringComparison.OrdinalIgnoreCase)));
            }

            if (price != null)
            {
                priceRanges[price.Value].Selected = true;
                return View(products.Where(p =>
                {
                    return price.Value switch
                    {
                        1 => p.UnitPrice < 1_000_000,
                        2 => 1_000_000 <= p.UnitPrice && p.UnitPrice < 10_000_000,
                        3 => 10_000_000 <= p.UnitPrice,
                        _ => true,
                    };
                }));
            }

            return View(products);
        }

        // GET: ProductsController/Details/5
        public ActionResult Details(int id)
        {
            var product = productRepository.GetById(id);
            if (product == null)
                return NotFound();
            return View(product);
        }

        // GET: ProductsController/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = GetCategoryIdList();
            return View();
        }

        // POST: ProductsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product)
        {
            try
            {
                if (ModelState.IsValid)
                    productRepository.Insert(product);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.CategoryId = GetCategoryIdList();
                ViewBag.Message = ex.Message;
                return View(product);
            }
        }

        // GET: ProductsController/Edit/5
        public ActionResult Edit(int id)
        {
            var product = productRepository.GetById(id);
            if (product == null)
                return NotFound();

            ViewBag.CategoryId = GetCategoryIdList();
            return View(product);
        }

        // POST: ProductsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Product product)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    product.ProductId = id;
                    productRepository.Update(product);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                ViewBag.CategoryId = GetCategoryIdList();
                return View(product);
            }
        }

        // GET: ProductsController/Delete/5
        public ActionResult Delete(int id)
        {
            var product = productRepository.GetById(id);
            if (product == null)
                return NotFound();
            return View(product);
        }

        // POST: ProductsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Product product)
        {
            try
            {
                productRepository.Remove(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(product);
            }
        }

        private IEnumerable<SelectListItem> GetCategoryIdList()
        {
            int n = 10;
            var list = new List<SelectListItem>(n);
            for (int i = 1; i <= n; i++)
            {
                list.Add(new SelectListItem(i.ToString(), i.ToString()));
            }
            return list;
        }
    }
}

EStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/w3.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        @if (Context.Session.GetInt32("MemberId") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Index">Members</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                            </li>
                            @if (Context.Session.GetInt32("MemberId") == 0)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Orders" asp-action="Report">Report</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Logout" asp-action="Index">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Login" asp-action="Index">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>